export const GET_USER="GET_USER"
export const SET_TOKEN="SET_TOKEN"
export const SET_USER="SET_USER"
export const DELETE_TOKEN="DELETE_TOKEN"
export const RESET ="RESET"

export const SET_CONNECTION ="SET_CONNECTION"

export const ADD_COLLECTION="ADD_COLLECTION"
export const ADD_COLLECTIONS="ADD_COLLECTIONs"
export const SET_COLLECTIONS="SET_COLLECTIONS"
export const DELETE_COLLECTION="DELETE_COLLECTION"
export const UPDATE_COLLECTION="UPDATE_COLLECTION"


export const SET_FUNCTIONAL_DATA="SET_FUNCTIONAL_DATA"